### ISSUE TITLE
Third party shortcodes into AdSense?

### ISSUE THREAD

**Issue by oVerde** [rene-hermenau/quick-adsense-reloaded#10]
Hey there, I've tried to insert third party plugins' shortcodes to the QUADS' AdSense tables, but the ad won't show on page. Just when I add the usual HTML tags etc.

I use this WP Plugin to manage my Ads, schelude them etc, it's important to the website health, and it work over shortcodes. How can I circumvent this?

**Comment by rene-hermenau** [comment]
Hi, you can try to change the load priority of the plugin. Use a low setting like 5 and a very high like 200 and check if this is helpful

**Comment by oVerde** [comment]
Tried: 1, 5, 20, 200, 500
None worked ):

![captura de tela 2016-08-02 as 12 13 56](https://cloud.githubusercontent.com/assets/1839750/17333061/4e32905c-58a7-11e6-9dc4-fd897d2a53fc.png)
![captura de tela 2016-08-02 as 12 13 42](https://cloud.githubusercontent.com/assets/1839750/17333062/4e407712-58a7-11e6-93eb-1c51db26d273.png)
![captura de tela 2016-08-02 as 12 13 27](https://cloud.githubusercontent.com/assets/1839750/17333063/4e4b25c2-58a7-11e6-8e8d-00eaa2ed2d75.png)

**Comment by rene-hermenau** [comment]
Please try the update: https://github.com/rene-hermenau/quick-adsense-reloaded/tree/1.1.7
and let me know if its working

**Comment by oVerde** [comment]
Didn't solved too.. 
This is the theme's code, I think it might be the problem?
![captura de tela 2016-08-03 as 21 28 10](https://cloud.githubusercontent.com/assets/1839750/17386147/139f78fc-59be-11e6-80fa-084afe5ec003.png)

**Comment by rene-hermenau** [comment]
I did another update. Please try again

**Comment by oVerde** [comment]
Is it okay to the rep be at these dates?
I'm following with the master download https://github.com/rene-hermenau/quick-adsense-reloaded/archive/master.zip

![captura de tela 2016-08-04 as 13 41 05](https://cloud.githubusercontent.com/assets/1839750/17409478/d82648ae-5a45-11e6-9d33-d27dd42f7f86.png)

**Comment by oVerde** [comment]
WORKED! 
LOV U! ahaha thanks a lot
